### ISSUE TITLE
Idea/Suggestion: 3D Node Stacking and View Port Navigation

### ISSUE THREAD

**Issue by mjcloutier** [projectstorm/react-canvas#1]
projectstorm has some awesome projects in the works here! I had one minor suggestion regarding react-canvas that would really put an edge on using the react-diagram/react-panels/react-canvas features for building a visual scripting language.

Most visual scripting languages are 2D and can get quite cluttered when they grow in complexity. It would be amazing if react-canvas could have a 3D rotating view canvas and ability to drag/select nodes and stack nodes behind each other in another plane. A dev could use VR, or a space mouse, or finger/apple pencil on a tablet to build complex programming structures.

**Comment by dylanvorster** [comment]
Hi @mjcloutier while I love the enthusiasm and excitement around such an addition, moving to a 3d plane is a completely different project and should probably be tackled with engines such as unity / unreal. Its already a massive challenge trying to build pluggable graphics libraries which work in 2D, moving to 3D would make this near impossible for a single person to get such a project off the ground. I think I will first try do all of this in 2D, and maybe one day if this project is still kicking, we can have a go at incorporating some 3D elements :)

But seriously though, thanks for the kind words and encouragement :D
